# Generated by Django 2.2 on 2019-04-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter',
            name='label',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
